apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hostname-deployment
spec:
  selector:
    matchLabels:
      app: flask-hostname-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-hostname-deployment
    spec:
      containers:
        - name: flask-hostname-container
          image: ariqbasyar/flask-hostname:3.8-slim
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
              name: flask-port
